name: CD

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    if: "!contains(${GITHUB_REF#refs/*/}, 'v0.'')"
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Create Release
        run: gh release create ${GITHUB_REF#refs/*/} --generate-notes
  pre-release:
    if: contains(${GITHUB_REF#refs/*/}, 'v0.'')
    name: Pre-Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Create Pre-Release
        run: gh release create ${GITHUB_REF#refs/*/} --generate-notes --pre-release
