name: CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - bin/**
      - "**.md"

jobs:
  bump-version:
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Bump Version
        id: bump-version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          default_bump: false
          dry_run: true
          fetch_all_tags: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
    outputs:
      new_version: ${{ steps.bump-version.outputs.new_version }}
      changelog: ${{ steps.bump-version.outputs.changelog }}
  release:
    if: needs.bump-version.outputs.new_version
    needs:
      - bump-version
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Generate Changelog
        run: echo "${{ needs.bump-version.outputs.changelog }}" >> /tmp/CHANGELOG.md
      - name: Generate New Version
        run: echo "${{ needs.bump-version.outputs.new_version }}" >> /tmp/VERSION.md
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            /tmp/CHANGELOG.md
            /tmp/VERSION.md
