name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - bin/**
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - bin/**
      - "**.md"

env:
  GO_VERSION: ^1.17

jobs:
  lint:
    name: Lint
    uses: strongishllama/github-actions/.github/workflows/golang-lint.yaml@main
  generate-readme:
    if: github.ref == "refs/heads/main" && github.event_name == "push"
    needs:
      - lint
    name: Generate Readme
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Generate Readme
        run: |
          curl -Lo ./gha-docs.tar.gz https://github.com/matty-rose/gha-docs/releases/download/v0.15.2/gha-docs-v0.15.2-linux-amd64.tar.gz
          tar -xzf gha-docs.tar.gz gha-docs
          chmod +x gha-docs
          ./gha-docs generate -o README.md action.yaml
      - name: Commit Readme
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: "docs: automated update of README.md"
          commit_user_name: GitHub Actions
          commit_user_email: github-actions@millhouse.dev
          file_pattern: README.md
  build-binaries:
    if: github.ref == "refs/heads/main" && github.event_name == "push"
    needs:
      - lint
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build Binaries
        run: ./build-all.sh
      - name: Commit Binaries
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: "ci: automated build of binaries"
          commit_user_name: GitHub Actions
          commit_user_email: github-actions@millhouse.dev
          file_pattern: bin/
