name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    uses: strongishllama/github-actions/.github/workflows/golang-lint.yaml@main
  build-binaries:
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - name: Build Binaries
        run: ./build-all.sh
      - name: Commit Binaries
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: "ci: automated build of binaries"
          commit_user_name: GitHub Actions
          commit_user_email: github-actions@millhouse.dev
          file_pattern: bin/
